### ISSUE TITLE
Evaluate self-hosted ephemeral macOS GitHub Actions runner solutions

### ISSUE THREAD

**Issue by stephanosio** [zephyrproject-rtos/infrastructure#158]
Currently, Zephyr self-hosted macOS GitHub Actions runners run the GitHub Actions workflows directly on the host operating system of the Mac Minis and are non-ephemeral.

They were implemented in such way mainly because there was no readily available solution for orchestrating macOS GitHub Actions runner VMs.

That is no longer the case and there are now a few open source solutions available for orchestrating macOS GitHub Actions runner VMs:

* [Cilicon](https://github.com/traderepublic/Cilicon)
* [ekiden](https://github.com/mirego/ekiden)

Evaluate these and, if feasible, migrate the current macOS self-hosted runner infrastructure to use them.

**Comment by kgantchev** [comment]
> Currently, Zephyr self-hosted macOS GitHub Actions runners run the GitHub Actions workflows directly on the host operating system of the Mac Minis and are non-ephemeral.  

Hi, @stephanosio,

I don't mean to be intrusive or disruptive in any way, but I see you're having problems with your self-hosted MacOS GitHub Actions runners. I'm the co-founder of [FlyCI](https://flyci.net), and if I may make a suggestion here, it might be a good idea to try our GitHub Actions runners. We offer M1 and M2 runners that are **ephemeral**.

The installation is effortless and you won't have to deal with doing any orchestration or self-hosting of the runners. It should be a straightforward drop-in for you and it should resolve this issue.

1. Install [FlyCI app](https://github.com/apps/flyci-prod) and
2. Easily replace one line of code and start using FlyCI runners:
``` diff
jobs:
 ci:
-    runs-on: macos-latest
+    runs-on: flyci-macos-large-latest-m1
   steps:
   - name: 👀 Checkout repo
     uses: actions/checkout@v4
```

Since your repo is **public**, you get **500 mins/month of free M1 runner usage** with the `flyci-macos-large-latest-m1` runner.

I hope this helps and I'm standing by should you have any questions.

Best Regards,
Kiril Gantchev
CEO and co-founder at [FlyCI](https://flyci.net/)

**Comment by stephanosio** [comment]
Sorry; but, GitHub runner per-minute prices are completely absurd (as in we would be paying over $300 per PR if we used GitHub runners), and being 2x cheaper than the GitHub simply won't cut it.

**Comment by kgantchev** [comment]
Hi @stephanosio, I completely understand your concern. 

I reviewed your GitHub actions history and estimate that your GitHub actions are roughly a couple of hours per month (~120 mins or so). Our **free tier** for public repositories is 500 mins/month on the M1 chip, which would probably run about 2x faster. Are you projection an increase in your build frequency or build time beyond 500 mins/month? Or are you estimating that with a coupe of commits per build, you'll exceed the 500 mins/month?

**Comment by stephanosio** [comment]
We already use M1 for macOS runners and every CI run takes over 1000 minutes. At this time, we are not looking for third-party macOS CI providers unless their cost is comparable to renting Mac Minis.

**Comment by kgantchev** [comment]
Got it. Thanks for the clarification. Again, sorry if my comment was intrusive... we're just trying to help where we can.

**Comment by stephanosio** [comment]
Self-hosted macOS GitHub Actions runners have been deployed using Cilicon.

Runner group: zephyr-runner-v2-macos-arm64-2xlarge
